name: Release frontend dev

on:
    push:
        branches:
            - dev

jobs:
    send-start-deploy-telegram-message:
        name: Send Telegram message
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v2

            - name: Send Telegram message
              uses: proDreams/actions-telegram-notifier@main
              with:
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
                  thread_id: ${{ secrets.TELEGRAM_TOPIC_ID }}
                  status: info
                  notify_fields: 'repository,branch,commit,workflow'
                  title: 'Build Dev started'

    build-and-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: '22.x'

            - name: Install dependencies and build
              run: |
                  npm ci
                  npm run start:build

            - name: Create ZIP archive of /dist
              run: |
                  zip -r remnawave-frontend.zip ./dist

            - name: Create or update dev tag
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git tag -f dev-build
                  git push origin refs/tags/dev-build --force

            - name: Create or update GitHub Release for dev
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: dev-build
                  name: Dev Build
                  prerelease: true
                  files: |
                      remnawave-frontend.zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    send-telegram-message:
        name: Send Telegram message
        needs: [build-and-release]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v2

            - name: Send Telegram message
              uses: proDreams/actions-telegram-notifier@main
              with:
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
                  thread_id: ${{ secrets.TELEGRAM_TOPIC_ID }}
                  status: success
                  notify_fields: 'repository,branch,commit,workflow'
                  title: 'Build finished'

    notify-on-error:
        runs-on: ubuntu-latest
        needs: [build-and-release]
        if: failure()
        steps:
            - name: Checkout source code
              uses: actions/checkout@v2

            - name: Send Telegram message
              uses: proDreams/actions-telegram-notifier@main
              with:
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
                  thread_id: ${{ secrets.TELEGRAM_TOPIC_ID }}
                  status: error
                  notify_fields: 'repository,branch,commit,workflow'
                  title: 'Build dev failed'
